process.env.SERVICE_BUS_CONNECTION_STRING = 'testConnectionString'
process.env.SERVICE_BUS_QUEUE_NAME = 'testQueueName'
process.env.AZURE_BLOB_SERVICE_URL = 'testBlobServiceUrl'
process.env.SMART_INCIDENT_REPORTING_BASE_URL = 'https://sir-base-url.gov.uk'
process.env.CONTENT_SAFETY_ENDPOINT = 'https://example.cognitiveservices.azure.com/'
process.env.CONTENT_SAFETY_KEY = 'test-key'
process.env.LOG_LEVEL = 'silent'